Adding additional recommendations
qiyunzhu/woltka pull request #121
Opened 2021-05-21 17:35 UTC by mortonjt

Added a couple of comments on performing paired-end alignment and quality filtering that could help future users of this tool.

2021-05-21 20:49 UTC, qiyunzhu requested changes
@mortonjt Thanks for contributing to the documentation! Looks good. Just a small typo.

2021-05-21 20:49 UTC, qiyunzhu commented on doc/wol.md
> +**Note**: You can also run Bowtie2 manually using your choice of parameters, or using other aligners and corresponding databases. Woltka is designed for flexibility.  For instance, you can run Bowtie
Should be "paired-end reads".

2021-05-21 21:19 UTC, mortonjt commented on doc/wol.md
> +**Note**: You can also run Bowtie2 manually using your choice of parameters, or using other aligners and corresponding databases. Woltka is designed for flexibility.  For instance, you can run Bowtie
```suggestion
**Note**: You can also run Bowtie2 manually using your choice of parameters, or using other aligners and corresponding databases. Woltka is designed for flexibility.  For instance, you can run Bowtie2 to handle paired-ends reads as follows
```

2021-05-21 21:20 UTC, mortonjt reviewed
Addressing typo

2021-05-29 05:24 UTC, qiyunzhu approved these changes
I think it is good to go now.

2021-05-29 05:24 UTC, merged